(NULL, 'Dog', 'Albus', 'M', '2001', 'abdulazizk', 1),
(NULL, 'Cat', 'Sirius', 'M', '2009', 'abdulazizk', 2),
(NULL, 'Bird', 'Dobbie', 'F', '2013', 'abdulazizk', 3),
(NULL, 'Snake', 'Hermione', 'M', '2005', 'abdulazizk', 3),
(NULL, 'Monkey', 'Buzz', 'F', '2016', 'abdulazizk', 4),
(NULL, 'Turtle', 'Toffee', 'M', '2000', 'abdulazizk', 5),
(NULL, 'Rabbit', 'Leia', 'M', '2006', 'abdulazizk', 5),
(NULL, 'Dog', 'Ghost', 'F', '2017', 'abdulazizk', 6),
(NULL, 'Horse', 'Ringo', 'M', '2010', 'abdulazizk', 7),
(NULL, 'Fish', 'Nemo', 'F', '2018', 'abdulazizk', 8),
(NULL, 'Goat', 'Boo', 'M', '2015', 'abdulazizk', 8),
(NULL, 'Shark', 'Doo Doo', 'M', '2018', 'abdulazizk', 9),
(NULL, 'Pig', 'Oak', 'M', '2017', 'abdulazizk', 10),
(NULL, 'Dog', 'Nully', 'F', '2017', 'abdulazizk', 11),
(NULL, 'Spider', 'Gregari', 'M', '2010', 'abdulazizk', 12),
