(NULL, '2016-08-21', 'Got ran over by a car and broke his back left leg. He will need surgery and 3 checkup appointments', 'TannerH', '182'), 
(NULL, '2015-08-24', 'Ran into a pole and cracked his skull. He will need surgery to stabilise his skull', 'TannerH', '183'), 
(NULL, '1988-06-23', 'Got shot by a hunter and broke his wing. He will need to be put down', 'TannerH', '184'), 
(NULL, '2016-08-15', 'Ran into the street and got hit by a car. He broke his toe and will need to be put down', 'TannerH', '185'), 
(NULL, '2018-06-02', 'Cut himself on some wire. He will need some pills to keep it from being infected', 'TannerH', '186'), 
(NULL, '2017-05-23', 'Ate too much grass and got sick. He will need some laxitives to help him get it back out', 'TannerH', '187'), 
(NULL, '2018-01-01', 'Got half eaten by a bear and will need to be put down', 'TannerH', '188'), 
(NULL, '2015-06-28', 'Broke his leg and will need a cast to stabilise it.', 'TannerH', '189'), 
(NULL, '2001-03-09', 'Ate some bleech and will need some laxitives to get it out of his system.', 'TannerH', '190'), 
(NULL, '2016-02-01', 'Got a little overweight and will need to be put on a diet.', 'TannerH', '191'), 
(NULL, '2018-02-02', 'Fell off a rock and cracked his shell. His shell will need to be glued back together.', 'TannerH', '192'), 
(NULL, '2015-05-05', 'Got hit by a 4-Wheeler and broke his front left leg. His leg will need to be amputated.', 'TannerH', '193'), 
(NULL, '2015-04-04', 'Ate too much food and needs to be put on a diet.', 'TannerH', '194'), 
(NULL, '2018-06-06', 'Got worms and will need to be worked and some bedrest.', '195'), 
(NULL, '2016-05-05', 'Got hit by a boat and will need to be put down.', 'TannerH', '196'),
